
    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="<?php echo base_url() ?>img/profile.png" alt="">
                    <!--<img class="img-responsive" src="<?php echo base_url(); ?>img/wt-cartoon-1.jpg" alt="">-->
                    <div class="intro-text">
                        <span class="name"><?php echo $sitetitle?></span>
                        <hr class="star-light">
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section >
        <div class="container">
            <div class="row">
                <div class="col-lg-12">	    
					<div class="intro-text">
					    <p>
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
						    This application does......
					    </p>
					</div>
                </div>
            </div>
        </div>        
    </section>



